### PR TITLE
Fix an error caused by trying to cast a pointer to an unsigned long.

### PR DESCRIPTION
**Pull request by shawnw**
Fixes issue #34.

### CODE REVIEW

**Comment by imneme** [comment]
You don't need the stdint include; all its definitions and more are provided by inttypes.

**Comment by shawnw** [comment]
Updated.

**Comment by imneme** [comment]
Can you collapse your change so that it is just one change to the line, not a change to add cstdint and then remove it?

**Comment by shawnw** [comment]
I have no idea how to do that short of making a new pull request from a new branch.

**Comment by imneme** [comment]
I think you can google “git merge two commits”. It gets me tips like [this one](https://stackoverflow.com/a/2568581/847987).

**Comment by shawnw** [comment]
Trying to push a squashed commit ends up not working unless I pull in changes from the github version and get the include you don't want right back. Plus I'm an idiot and removed it from the wrong file anyways. So nevermind this one; it's just a trivial a one-line change anyways and we've both wasted more time on these comments than it would have taken you to change it yourself. Sorry about that.

**Pull request closed without merging**
