### PR TITLE
Makefile: Fix install target.

### PR DESCRIPTION
**Pull request by gerasiov**
* Add DESTDIR support.
* Allow one to override PREFIX.

Signed-off-by: Alexander GQ Gerasiov <gq@cs.msu.su>

### CODE REVIEW

**Comment by NAThompson** [comment]
I've hit this bug as well. Looks like your fix is good to me.

**Comment by imneme** [comment]
I've merged a similar change that doesn't use `=?`. I don't think that's necessary. Feel free to complain if you're sure I'm mistaken.

**Comment by NAThompson** [comment]
Just tested your fix and it works.

BTW since all that the `install` target does is copy header files into some syspath, there's no need to have it depend on the `all` target, esp. if the system doesn't have `gcc`.

Just my two bits!

**Comment by imneme** [comment]
Interesting point about the dependency on `all`.

But it does serve as a sanity check. If those things don't compile, it's questionable whether it's a good idea to install the headers. And, if the system doesn't have a compiler, installing a header-only library doesn't seem like it makes a lot of sense.

**Comment by NAThompson** [comment]
@imneme : I was mainly thinking about when Microsoft comes out with its command line terminal this summer only `msvc` will be expected to be available on Windows. (Of course, they could override the compiler on the command line.) More of a nitpick I admit.

**Pull request closed without merging**
